# This workflow will install Python dependencies, run tests and deploy the application to the Fly environment

name: Upload to Fly

on:
  push:
    branches: [ "main" ]

jobs:
  runner-job:
    runs-on: ubuntu-latest
  # Service containers to run with `runner-job`
    services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres
          # Provide the password for postgres
          env:
            POSTGRES_PASSWORD: postgres
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            # Maps tcp port 5432 on service container to the host
            - 5432:5432



    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Install dependencies
      run: |
        poetry install
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v1
    - name: Start ChromeDriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - name: Initialize database
      run: |
        poetry run python3 src/init_db.py
      env: 
        DATABASE_URL: postgres://postgres:postgres@localhost:5432
    - name: Start Flask server
      run: |
        poetry shell
        echo "Entered the Poetry shell"
        nohup python3 src/index.py
        echo "Started Flask server"
        sleep 10
      env: 
        DATABASE_URL: postgres://postgres:postgres@localhost:5432
    - name: Test with Robot
      run: |
        poetry run robot src
    - name: Export requirements.txt
      run: |
        poetry export --without-hashes --format=requirements.txt > requirements.txt
    - name: Set up flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy to Fly
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
